spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/camunda
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    database-platform: org.hibernate.dialect.MySQL8Dialect
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: einsetzen
    password: einsetzen
  
camunda:
  bpm:
    admin-user:
      password: Pa55w0rd
      id: admin
    filter:
      create: show all
    history-level: ACTIVITY

logging:
  level:
    root: WARN
    io.remedymatch: INFO
