server:
  port: 8085
camunda:
  bpm:
    admin-user:
      password: Pa55w0rd
      id: admin
    filter:
      create: show all
    history-level: ACTIVITY
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/camunda
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    driver-class-name: org.postgresql.Driver
    username: rmbe
    password: rmbe